securego/gosec

- core/analyzer.go
This should handle issue #9 more gracefully.
> Handle import error rather than panic on failure

- README.md
> Fix exclude documentation

- filelist.go
The exclude flag was only using filepath.Match which isn't intuitive
compared with some other command line tools. Added a couple of
additional cases to handle relative paths.
Fixes issue #16
> Expand cases accepted by -exclude

- rules/sql.go
- rules/sql_test.go
This prevents the string concat tests flagging a false positive if
joining two literal strings (eg "SELECT * FROM " + " table" ... )
or with a constant (eg const tab = "name"; "SELECT * from " + tab)
> Better SQLi testing

- output/formatter.go
@gcmurphy @callidus
The encoding/csv package will take care of quoting, double-quoting,
and other CSV quirks -- avoids having to fiddle with text templates.
> Use encoding/csv for CSV output

- core/analyzer.go
It should have been in the context object, not the analyzer
> Fixing config

- .travis.yml
> Add travis ci profile

- main.go
- rulelist.go
Mostly a tidy up. Fixed a couple of spelling errors as well.
> Fix usage information

- main.go
Signed-off-by: Levi Gross levi@levigross.com
> Make sure to exit 1 if we find an issue

- rules/sql.go
> Confirmed correct behavior for SQL tests

- output/formatter.go
- output/template.go
Hi! Not sure if this is something you want to include, but I made an HTML issue browser to make it easy to navigate through issues. The included HTML template uses react to render issues dynamically, and allows for filtering based on severity/confidence/type. Try it out and let me know what you think.
> Add support for HTML output

- core/helpers.go
This introduces a helper function that will significantly reduce the
number of false positives that occur due to the use of regexp based
call matching.
It resolves the object related to a CallExpr and checks that against the
supplied package and identifier name. If both of these match the
returned value is the CallExpr and Object.
> Add MatchCall helper that utilizes type checker

- main.go
Fix #55 
Also add HTML to usage description
> Command line fixes

- core/helpers.go
Allows direct call to GetCallObject.
> Split out MatchCallByObject into two functions

- tools.go
Add the ability to dump most of the context Info map for a file.
> Add some more useful debugging tools

- rulelist.go
- rules/fileperms.go
- rules/fileperms_test.go
In addition configuration file may be used to set the permission level.
Closes #53
> Ensure os.OpenFile file permissions are checked

- core/analyzer.go
- rules/rand.go
The import information was being persisted between files. This was
causing false positives.
Fixes #87
> Initialize fresh import info for each file

- core/analyzer.go
- core/helpers.go
- filelist.go
- main.go
- rules/fileperms.go
- rules/sql.go
- rules/tempfiles.go
- tools.go
> Address unhandled error conditions

- core/analyzer.go
- core/helpers_test.go
- rules/utils_test.go
Some files were being counted multiple times here and giving a skewed
result for line numbers processed.
Closes #100
> Recreate fileset each time we process a file

- main.go
> Fix recursive case on Windows platforms

- rules/tls.go
> Add the CHACHA20 to good ciphers in modern tls check

- issue_test.go
- output/formatter.go
I also removed the `gas` binary that had been committed to the cmd/gas directory.
> output/formatter: Issue.Line was already a string

- cmd/gas/main.go
Use the configured logger for all log messages.
> Sending log messages to multiple streams

- cmd/gas/main.go
- testutils/pkg.go
> Fix some gas warnings

- .travis.yml
- analyzer.go
- import_tracker_test.go
- issue.go
- rules/rulelist.go
Validate the tool from go version 1.7 onward
cc @gcmurphy
> Update the build file with more checks

- Godeps/Godeps.json
- README.md
- cmd/gas/main.go
- output/formatter.go
This is a fix for #173. 
cc @gcmurphy
> Add support for YAML output format

- Gopkg.lock
- rules/tls_config.go
Update the tls-observatory package and regenerate the TLS configuration with latest ciphers
Fixes #190
> Regenerate the TLS config

- analyzer.go
- cmd/gosec/main.go
- helpers.go
Move some utility functions into the helper
> Derive the package from given files

- .gitignore
- .goreleaser.yml
- Dockerfile
- Gopkg.lock
- Makefile
- README.md
> Use the goreleaser tool to perform releases

- cmd/gosec/main.go
> Add a flag to specify the severity for which the scanning will be failed

- README.md
- rules/blacklist.go
- rules/rulelist.go
- rules/rules_test.go
- rules/weakcrypto.go
- testutils/source.go
>  Add sha1 to weak crypto primitives

- rules/sql.go
This is another small update to the SQL ruleset. In certain cases, `fmt.Fprintf` can be used to push a vulnerable SQL statement into a buffer which then gets passed to a SQL query function. I gave rule G201 the ability to identify vulnerable `fmt.Fprintf` calls. If `os.Stdout` or `os.Stderr` are used as the buffer, then we mark it as a false positive. 
Example: `fmt.Fprintf(buff, "SELECT * FROM foo WHERE user='%s', bar)`
Please let me know if I should also add code samples to `testutils/source.go`
> Added Fprintf to Rule G201

- .gitignore
- Dockerfile
- Makefile
- README.md
- docker-entrypoint.sh
Refactor the `Dockerfile`:
* added `gcc` and `musl-dev` so `cgo` can operate
* update golang to latest 1.10.x
* multi-stage builds to have a minimal final image
* replace `docker-entrypoint.sh` (doesn't seem to be needed) with `gosec` binary
Final docker image built should be the same interface.
```
$ make image
Building the Docker image...
docker build -t securego/gosec:1.1.0-13-g6ca6e09 .
[+] Building 0.1s (14/14) FINISHED                                              
=> [internal] load Dockerfile                                             0.0s
=> => transferring dockerfile: 38B                                        0.0s
=> [internal] load .dockerignore                                          0.0s
=> => transferring context: 2B                                            0.0s
=> …
```
> refactor Dockerfile

- output/template.go
- resolves HTML escaping issues within the template
- resolves reference issues to reportInfo struct i.e. issues -> Issues, metrics -> Stats
> Fix the html template

- rules/errors.go
- testutils/source.go
Hello, first of all thank you for this project!
I would like to contribute, and I've started addressing issue #255.
I added a test case and the implementation, but the test are failing, and I can't get why. I tried reverse engineering the behaviour from other tests but it's clearly not working as expected.
Any help would be greatly appreciated :)
Thank you!
Fixes #255
> Whitelist strings builder

- helpers.go
- rules/bind.go
- testutils/source.go
> Fix the bind rule to handle the case when the arguments of net.Listen are returned by a function

- rules/errors.go
- testutils/source.go
> Do not flag the unhandled errors which are explicitly ignored

- README.md
> Update the README with some details about the configuration file

- analyzer.go
- cmd/gosec/main.go
- go.mod
- go.sum
- helpers.go
- helpers_test.go
> Remove GOPATH check to allow running gosec outside of GOPATH

- analyzer.go
- call_list_test.go
- import_tracker.go
- import_tracker_test.go
- testutils/pkg.go
> Track only the imports from the file which is checked

- analyzer.go
- analyzer_test.go
- errors.go
- issue.go
- rules/fileperms.go
- testutils/pkg.go
- testutils/source.go
> Fix error parsing when the loaded package is empty

- cmd/gosec/main.go
Refactor also how the issues are filtered by severity.
fixes #314
> Add a flag to filter issues by confidence

- cmd/gosec/main.go
- helpers.go
- helpers_test.go
- output/formatter.go
- output/formatter_suite_test.go
- output/formatter_test.go
> Fix the file path in the Sonarqube report and also add support for multiple root folders

- README.md
- analyzer.go
- analyzer_test.go
- rules/errors.go
- rules/rules_test.go
- testutils/source.go
> Fix the whitelist on G104 rule and add some documentation which describe how to configure the whitelist

- README.md
> Update README file with a note on dependencies

- README.md
- cmd/gosec/main.go
- helpers.go
- helpers_test.go
> Add support to exclude arbitrary folders from scanning

- renovate.json
(I think this will enable automerge for renovatebot)
> turn on automerge for renovate bot

- README.md
- rules/pprof.go
- rules/rulelist.go
- rules/rules_test.go
- testutils/source.go
> Add a rule which detects when pprof endpoint is automatically exposed

- rules/pprof.go
- testutils/source.go
> Fix the rule G108/pporf to handle the case when the pporf import has not name

- config.go
- config_test.go
> Convert the global settings to correct type when reading them from file

- call_list.go
- call_list_test.go
- helpers.go
- helpers_test.go
- rules/archive.go
- rules/bind.go
- rules/decompression-bomb.go
- rules/errors.go
- rules/integer_overflow.go
- rules/readfile.go
- rules/rsa.go
- rules/sql.go
- rules/ssrf.go
- rules/subproc.go
- rules/tempfiles.go
- rules/templates.go
- testutils/source.go
> Fix the errors rule whitelist to work on types methods

- call_list_test.go
- helpers.go
- testutils/source.go
> Fix the call list info to handle selector expressions

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .goreleaser.yml
- Dockerfile
- Makefile
- README.md
The release will trigger when a new tag is pushed.
> Automate the release process using a GitHub workflow

- README.md
- rules/implicit_aliasing.go
- rules/rulelist.go
- rules/rules_test.go
- testutils/source.go
fixes https://github.com/securego/gosec/issues/438
> Rule which detects aliasing of values in RangeStmt

- USERS.md
- testutils/pkg.go
> USERS.md typo

- helpers.go
- helpers_test.go
- issue_test.go
- rules/implicit_aliasing.go
- rules/sql.go
- testutils/source.go
- Improve the SQL concatenation and string formatting rules to be applied only in the database/sql context
- Make the heuristic case insensitive
- Handle multiple strings concatenation 
fixes #264 #369 #345
> Various improvements in the SQL rules

- cmd/gosec/main.go
When your repository has a branch which has `.go` suffix as a branch name (for example`fix/main.go`), gosec will cause errors. Because `git` command creates `.git/refs/heads/fix/main.go` file in your `.git` directory. Then, gosec scans it as a Go file.
This pull request will fix it ignore `.git` directory.
1. Create a branch which has .go suffix
`git checkout -b feature/ignore-dot-git-dir.go`
2. Run gosec
`gosec ./...`
3. It will cause following errors
```
gosec =                                                                           (git)-[feature/ignore-dot-git-dir.go] -? (m1)
gosec = cd cmd/gosec/ && go build && cd - && ./cmd/gosec/gosec ./...
~/work/src/github.com/hiroakis/gosec
[gosec] 2020/06/09 21:48:30 Including rules: default
[gosec] 2020/06/09 21:48:30 Excluding rules: …
```
> Exclude .git directory from scan

- helpers.go
- rules/rand.go
- testutils/source.go
> Extend the insecure random rule with more insecure random functions

- rules/readfile.go
- testutils/source.go
> Extend the rule G304 with os.OpenFile and add a test to cover it

- rules/tls.go
- testutils/source.go
> Improve the TLS version checking

- rules/decompression-bomb.go
- testutils/source.go
> Add io.CopyBuffer function to rule G110

- .github/workflows/ci.yml
- .github/workflows/release.yml
Also updated the release automation to release gosec with use Go 1.15
> Add Go 1.15 to the supported version and phase out the Go 1.12

- output/formatter.go
- output/sarif_format.go
I followed the example from the sonarqube formatter and guidance from the spec, which i linked in the code.
> fix for sarif which translates from issue severity to sarif level

- README.md
`-u` will ensure that users are updated the latest released version.
This way bugs are less likely to be reported that are already fixed.
> Add `-u` to local install instructions

- output/formatter.go
- output/formatter_test.go
- output/sonarqube_format.go
- sonar/types.go
* Migrate sonar types in a dedicated package
* CWE field is not supported by sonar Report so I removed it
> Migrate sonar types in a dedicated package

- cmd/gosec/main.go
This a proposition after exchanges with @ShreyasSubhedar in the PR #611 about text report colorization
> Allow the user to enable/disable colorization of the text report in the stdout

- .github/dependabot.yml
I haven't set up go dependencies management as there is already renovate to handle this.
> Define Dependabot configuration 

- .goreleaser.yml
> Add arm64 support

- report/html/template.go
This PR fixes the tag classes that did not work as initially intended.
> fix html report tag styling

- report/html/template.go
Update Bulma to 0.9.2 
Add Highlight Js
Change Filters and badges design
@ccojocar, @bakito , please have a look on the new design.
Would there be a way to have a preview that we could discuss ?
> Update Design of HTML report

- report/html/template.go
Add the favicon of Gosec on the report
> Add favicon for HTML template

- renovate.json
@ccojocar , This creates the onboarding PR
> add onboarding

- cmd/gosec/main.go
Hi @wongherlung , @ShreyasSubhedar would you mind checking this fix ?
> Fixes #644

- helpers.go
Signed-off-by: Cosmin Cojocar <ccojocar@cloudbees.com>
> Fix gosimple lint warning

- helpers.go
Signed-off-by: Cosmin Cojocar <ccojocar@cloudbees.com>
> Fix the unit tests

- rules/subproc.go
- testutils/source.go
resolves #659 
* add G204 detection for golang.org/x/sys/execabs
> Add G204 rule for sys/execabs

- rules/hardcoded_credentials.go
- testutils/source.go
This PR add new keyword to identify hardcoded credentials as discussed in this ticket #597
> feat: adding new keyword for hardcoded credentials

- USERS.md
We just added gosec to our standard Golang tooling and pipelines.
> Add SeatGeek to USERS.md

- cmd/tlsconfig/tlsconfig.go
- helpers_test.go
- rules/fileperms.go
- testutils/pkg.go
> Fix formatting issues with gofumpt

- report/html/template.go
This PR adds a summary to the html page
> add summary to html report

- report/html/template.go
sorry I messed up whitespaces in my last commit 
(looking forward to https://github.com/securego/gosec/pull/625 ;) )
> remove tabs

- .github/workflows/ci.yml
- .github/workflows/release.yml
Signed-off-by: Cosmin Cojocar <cosmin.cojocar@gmx.ch>
> Enable go 1.17 in the build and release workflows

- .golangci.yml
- analyzer.go
- analyzer_test.go
- cmd/gosec/main.go
- cmd/tlsconfig/tls_version_go14.go
- cmd/tlsconfig/tlsconfig.go
- import_tracker_test.go
- report/sarif/formatter.go
- rules/rules_test.go
- testutils/source.go
This enables two more linters : errorlint and gci
> chore(lint): enable errorlint and gci

- rules/errors.go
> Add os.Unsetenv to NoErrorCheck whitelist

- README.md
This PR updates the local installation instruction for Go1.16+.
> Update local installation instruction

- rules/tls.go
> Fix crash when parsing the TLS min version value

- README.md
- analyzer.go
- analyzer_test.go
- cmd/gosec/main.go
- cmd/gosecutil/tools.go
- issue.go
- report/formatter.go
- report/formatter_test.go
- report/sarif/builder.go
- report/sarif/formatter.go
- report/sarif/sarif_test.go
- rule.go
- rule_test.go
- rules/rulelist.go
- rules/rules_test.go
Add a new feature to track suppression info of GoSec. Details described in #723 
fixes #723
> Suppression support

- rules/tempfiles.go
- testutils/source.go
See individual commits for details.
> Find more tempdirs

- report/sarif/formatter.go
> Use the CWE name as a name in the SARIF report

- cmd/gosec/main.go
> added recursive flag -r to skip specifying ./... path

- rules/templates.go
> Update the description message of template rule

- rules/subproc.go
- testutils/source.go
Signed-off-by: Ziqi Zhao <zhaoziqi9146@gmail.com>
fix #831
> fix G204 bugs

- cmd/gosec/main.go
> Check the suppressed issues when generating the exit code

- report/text/template.txt
> fix: handle nil CWE pointer in text template

- cwe/types.go
- report/golint/writer.go
- report/junit/formatter.go
- report/sarif/formatter.go
> fix: make sure that nil Cwe pointer is handled when getting the CWE ID

- Makefile
> Add vulncheck to the test steps

- cwe/data.go
> Add CWE-676 to cwe mapping

- Makefile
> Update Go version to 1.19 in the makefile

- rules/readfile.go
- testutils/source.go
> Track back when a file path was sanitized with filepath.Clean

- report/sarif/formatter.go
- report/sarif/sarif_test.go
> Fix rule index reference into sarif report

- rules/readfile.go
- testutils/source.go
- tools/tools.go
Fix for issue #937 including test case.
> Fix for #937

- .golangci.yml
- analyzer_test.go
- call_list_test.go
- config_test.go
- flag_test.go
- helpers_test.go
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
> enable ginkgolinter linter

- README.md
Upgrade actions/checkout from v2 to v3 in GitHub actions examples.
> README: upgrade GitHub action in examples

- .github/workflows/release.yml
- .goreleaser.yml
> Update cosign to latest version in release Github action

- action.yml
> Update gosec image version to 2.16.0 in the Github action

- rules/implicit_aliasing.go
- testutils/source.go
**Related issues**
https://github.com/securego/gosec/issues/966
> Recognize struct field in G601

- .github/workflows/ci.yml
- .github/workflows/release.yml
> Update build script to go version 1.20.5

- README.md
> Update README file with new rule

- .github/workflows/ci.yml
- .github/workflows/release.yml
> Update to Go version 1.19.11 and 1.20.6

- go.mod
> Fix dependencies after bot update

- go.mod
- go.sum
- rules/hardcoded_credentials.go
> Switch to a maintained fork of zxcvbn module

- .github/workflows/ci.yml
- .github/workflows/release.yml
> Update to go version 1.20.7 and 1.19.12

- .github/workflows/ci.yml
- .github/workflows/release.yml
> Update to latest go version

- rules/unsafe.go
- testutils/source.go
> Update the list of unsafe functions detected by the unsafe rule

- helpers.go
- helpers_test.go
> Handle new function when getting the call info in case is overriden

- analyzer.go
> Handle gracefully any panic that occurs when building the SSA representation of a package

- .github/workflows/release.yml
- action.yml
- Update cosign version to v2.2.0
- Update gosec to version 2.18.1 in the action
> update action version

- action.yml
> Update gosec version to 2.18.2 in the action

- README.md
> Update local installation instructions by removing the details for Go 1.16

- .github/workflows/ci.yml
- Makefile
- perf-diff.sh
This step will measure the scan performance difference against the master version.
> Add a build step to measure the scan perfomance

- .github/workflows/release.yml
Signed-off-by: Cosmin Cojocar <ccojocar@google.com>
> Update cosign version to v2.4.0 in release github workflow

- action.yml
> Update gosec in github action to v2.21.0

- report/sarif/data.go
> Update the SARIF schema URL

- report/sarif/builder.go
> Populate the fixes only when autofix is not empty

- action.yml
> Update gosec in github action to 2.22.0

- .github/workflows/ci.yml
- .github/workflows/release.yml
> Update to go version 1.23.5 and 1.22.11

- .github/workflows/ci.yml
- .github/workflows/release.yml
> Update to go version 1.23.6 and 1.22.12

- .github/workflows/ci.yml
- .github/workflows/release.yml
> Add support for go 1.24 and phased out support for go 1.22

- action.yml
> Update gosec version in the GitHub action to v2.22.1

- .github/workflows/ci.yml
- .github/workflows/release.yml
> Update to go version 1.24.1 and 1.23.7

- report/html/template.html
> Update the integrity sha for babel dependency in html report

- .github/workflows/ci.yml
- .github/workflows/release.yml
> Update go version to 1.24.2 and 1.23.8

- analyzers/util.go
This can occur when there is a compilation issue into the code.
fixes #1326
> Handle nil file when creating a new issue

- cmd/gosec/main.go
> Update the AI provider API key value when provided as an argument

- .github/workflows/ci.yml
- .github/workflows/release.yml
> Update to go version 1.24.3 and 1.23.9
