securego/gosec

rulelist.go
rules/httpoxy.go
rules/httpoxy_test.go

Go code running under CGI is vulnerable to httpoxy attack. See
https://httpoxy.org/ this checks for an import of net/http/cgi
that might indicate code may be run under CGI.
closes #1

Adding check for httpoxy

---

output/formatter.go

r: @gcmurphy 
This makes sure that `-fmt json` produces output that is a valid JSON document. 
Before:
```
$ gas -fmt json main.go | head -n6
{
"metrics": [
Files: 1,
Lines: 508,
Nosec: 0,
Issues: 1],
```
After:
```
$ gas -fmt json main.go | head -n7
{
"metrics": {
"files": 1,
"lines": 508,
"nosec": 0,
"issues": 1
},
```
In the future, would probably be better to serialize a struct with `encoding/json` instead of using templates.

Make sure -fmt json produces valid output

---

core/analyzer.go
core/issue.go
output/formatter.go

r: @gcmurphy 
Fixes bug #12, so escaping works now:
```
cs gas-test master $ gas -fmt json main.go
{
"issues": [
{
"severity": "HIGH",
"confidence": "LOW",
"details": "Potential hardcoded credentials",
"file": "main.go",
"code": "password := \"repro for escaping bug \u003c \u003e \u0026 ;\"",
"line": 4
}
],
"metrics": {
"files": 1,
"lines": 5,
"nosec": 0,
"found": 1
}
}
```
Parses correctly (using `jq` as example):
```
cs gas-test master $ gas -fmt json main.go | jq .
{
"issues": [
{
"severity": "HIGH",
"confidence": "LOW",
"details": "Potential hardcoded credentials",
"file": "main.go",
"code": "password := \"repro for escaping bug < > & ;\"",
"line": 4
}
],
"metrics": {
"files": 1,
"lines": 5,
"nosec": 0,
"found": 1
}
}
```

Use encoding/json for -fmt json output

---

rules/hardcoded_credentials.go

@gcmurphy @callidus 
Check right-hand side expr for literals when looking for hard-coded credentials.
Example file:
```Go
package main
func main() {
passwordBad := "password"
passwordOk := getPassword()
}
```
With these changes, the first line in `main` will still warn, but the second line will now be fine. Previously both lines would produce a warning.
Anecdotally (based on running this on Square's internal Go code base) the hard-coded credentials check almost always yields false positives, since it's a common pattern to read a secret from e.g. a file and then load it into a variable like "password" or "token" or such.

Smarter hard-coded credentials check

---

rulelist.go
rules/rand.go
rules/rand_test.go

@gcmurphy @callidus 
Detects the use of `rand.Read` from math/rand in a code base. It's easy to accidentally import math/rand instead of crypto/rand for such uses since they both have a read function with the same type signature. It doesn't warn on other uses, because those APIs are explicitly different from the crypto/rand ones so I think they're less likely to be misused. 
Minimal sample that triggers an issue:
```Go
package main
import (
"math/rand"
)
func main() {
bad, err := rand.Read(nil)
}
```
Whereas this does not trigger:
```Go
package main
import (
"crypto/rand"
)
func main() {
good, err := rand.Read(nil)
}
```

Detect use of rand.Read from math/rand

---

core/analyzer.go
main.go
rules/nosec_test.go

The logic around annotations (nosec) was broken, meaning they were
ignored by default and would not skip sub-blocks. This fixes the
problem and also adds a test to make sure it wont be broken in the
future. Closes #25

Fixing annotations

---

filelist.go

It is a little tricky that !os.IsNotExist(e) is not equal to os.IsExist(e) while the program is running on Windows.
[https://golang.org/src/os/error_windows.go](error_windows.go)
The default excluded filelist is "*_test.go" and the path name is invalid when call os.Stat() on Windows.
Take the following code for example:
```
package main
import (
"log"
"os"
)
func main() {
st, e := os.Stat("*_test.go")
if e != nil {
log.Println(e)
}
log.Println( "!os.IsNotExist:", !os.IsNotExist(e) )
log.Println( "os.IsExist:", os.IsExist(e) )
log.Println( "Status:", st )
}
```` 
The result on Linux:
```` 
2016/07/29 22:52:55 stat *_test.go: no such file or directory
2016/07/29 22:52:55 !os.IsNotExist: false
2016/07/29 22:52:55 os.IsExist: false
2016/07/29 22:52:55 Status: <nil>
```` 
The result on …

Fix os.IsExist() condition in filelist.Contains()

---

rules/bind.go
rules/fileperms.go
rules/hardcoded_credentials.go
rules/httpoxy.go
rules/rand.go
rules/rsa.go
rules/sql.go
rules/tempfiles.go
rules/templates.go
rules/tls.go
rules/unsafe.go
rules/weakcrypto.go

There are some cases where the '.' character would also match any
character and could lead to incorrect results. For example the
regular expression -  `^ioutils.WriteFile$' would match
ioutils.WriteFile, but also ioutils_WriteFile.
Additionally made sure that all regexp were declared using raw
strings to avoid any unnecesary string escaping that potentially
make the regexp difficult to read.

Fix incorrect regexp matches

---

core/analyzer.go
main.go
rules/bind_test.go
rules/errors_test.go
rules/fileperms_test.go
rules/hardcoded_credentials_test.go
rules/httpoxy_test.go
rules/nosec_test.go
rules/rand_test.go
rules/rsa_test.go
rules/sql_test.go
rules/subproc_test.go
rules/tempfiles_test.go
rules/templates_test.go
rules/tls_test.go
rules/unsafe_test.go
rules/weakcrypto_test.go

A CLI option can now be given to tell GAS it should parse data
from a JSON file. Fatal errors are given if the file is not
readable or is not valid JSON.

Adding a config block to the analyzer, parsed from JSON

---

core/analyzer.go
core/resolve.go
rules/subproc.go
rules/subproc_test.go

This is used in the subprocess launching test but will be added to
others as applicable.
I am also adding more (all) possible fields to the context info. Not
used in this patch but will be in the future.
This also closes #28

Try to resolve all elements in an expression to a known const

---

core/analyzer.go
main.go
rules/bind_test.go
rules/errors_test.go
rules/fileperms_test.go
rules/hardcoded_credentials_test.go
rules/httpoxy_test.go
rules/nosec_test.go
rules/rand_test.go
rules/rsa_test.go
rules/sql_test.go
rules/subproc_test.go
rules/tempfiles_test.go
rules/templates_test.go
rules/tls_test.go
rules/unsafe_test.go
rules/weakcrypto_test.go

This re-works the way that CLI options are passed through to the
analyzer so that they can act as overrides for config options. If
not given on the CLI, options will come from a config file. If no
file is used then a default value is chosen.
Two lists are also populated with tests to include or exclude.
These lists are not used for now but will eventually replace the
way we select test to run in a future patch to follow.  NOTE that
the "exclude" CLI option has been repurposed to mean
excluded rules, a new "skip" option has been added to replace
the old behaviour.

Configuration

---

main.go

This looks to have been a typo in the supported output formats.

Clarified output format options.

---

filelist.go

fixes #45 
filepath.Match() requires the entire path is matched, prefixing ** allows `*_test.go` to work in multiple packages.

prefix patterns with **/ to match subdirectories

---

filelist.go
main.go

Effectively using filepath.Glob to build a set of files and directories
to exclude from the scan.
(ref: https://golang.org/pkg/path/filepath/#Glob)
Potentially will resolve #50 #51

Refactor path matching logic

---

rules/rand.go
rules/rand_test.go

work in progress - could use a lot of refactoring
Fix for https://github.com/GoASTScanner/gas/issues/43 by resolving full package paths instead of regex on package name.

rand: resolve math/rand package

---

core/call_list.go

A call list is a way of grouping a number of packages and function calls
into a blacklist or whitelist. Could be useful to exclude certain
functions from results or looking for a specific set of functions.

Add an experimental way to whitelist/blacklist calls

---

core/analyzer.go
core/helpers.go
rules/blacklist.go
rules/blacklist_test.go
rules/weakcrypto.go

There has been a number of false positives using the regexp matching. This approach attempts to resolve it in a backwards compatible way. The 'Uses' map does not appear to be populated with the same level of detail in Go 1.5 so using GetCallObject was not sufficient. 
Additionally this should address the blacklist imports issue where we were reporting an error for initialization only imports.

Track package imports and aliases

---

core/helpers.go
rules/rand.go

Updated the `rand` rule to use the helper added by https://github.com/GoASTScanner/gas/pull/67
Also changed `MatchCallByObject` to `MatchCallByPackage` since it only matches functions on a package, not objects.

rand: use a MatchCallByPackage helper

---

core/analyzer.go
rulelist.go
rules/bind.go
rules/blacklist.go
rules/errors.go
rules/fileperms.go
rules/hardcoded_credentials.go
rules/hardcoded_credentials_test.go
rules/httpoxy_test.go
rules/rand.go
rules/rsa.go
rules/sql.go
rules/subproc.go
rules/tempfiles.go
rules/templates.go
rules/tls.go
rules/unsafe.go
rules/weakcrypto.go

This change will allow rules to register interest in multiple AST nodes. This change was needed to implement the fix for hardcoded credentials without creating an additional rule to handle the GenDecl case.

Adjust rule interface to allow interest in multiple ast node types 

---

rules/hardcoded_credentials.go
rules/hardcoded_credentials_test.go

The following code would create a panic condition:
const foo, bar = "some thing"
Fixes #84

Handle inbalanced declaration of constants

---

core/analyzer.go
rules/unsafe.go

Unsafe is not tracked in Package.Imports(), the regexp was not explicit
enough and foounsafe.Blah() would trigger an error.

Update unsafe rule to match package explicitly

---

core/analyzer.go

This commit fixes the nosec feature to check for '#nosec' instead
of 'nosec'.  This should help reduce false positives associated
with comments that have 'nosec' in them somewhere.

Fix nosec to work as documented

---

.gitignore
filelist.go
filelist_test.go
main.go
main_test.go
vendor.conf
vendor/github.com/ryanuber/go-glob/LICENSE
vendor/github.com/ryanuber/go-glob/glob.go

Changes:
- any path suffixed with `/...` will now work.
- changes to fileList and how the `-skip` values are handled necessary to support this.
- Golang does not support arbitrary length globbing in filepaths so inclusion of go-glob for simple string glob matching on `-skip` paths.
- Addition of vndr tool to manage dependencies.
- fixed capitalization of `filelist`. Some comments had `fileList` and it's technically 2 words so updating per Go defacto style conventions to `fileList`.
I'm a big fan of including the vendor directory as it protects projects from dependencies becoming unavailable. This isn't my project though so if you don't want it, or want a tool other than `vndr`, just let me know and I'll update.
~~Still working on some tests, will remove WIP later today once I've …

adding support for arbitrary paths with ellipses

---

filelist.go
main.go

Only need to log if we're skipping a file or if we're processing it.
Should also use the [gas] prefix to aid filtering.

Reduce logging messages a tad

---

README.md
main.go

Updated Readme description of skip and re-added a little verbosity to the CLI description.
closes #103

updating skip cli help and readme description

---

rules/hardcoded_credentials.go
rules/hardcoded_credentials_test.go

This is a partial bandaid fix for #108 until we introduce the entropy check suggested in #105.

Ensure hardcoded credentials check only considers constant strings

---

core/analyzer.go
main.go
rules/errors_test.go
rules/fileperms_test.go
rules/hardcoded_credentials_test.go
rules/httpoxy_test.go
rules/nosec_test.go
rules/rand.go
rules/rand_test.go
rules/sql_test.go
rules/subproc_test.go
rules/tls_test.go

Type checking failures were previously not reported and the file was
silently ignored. This change will report the error and halt further
processing.
Relates to #111

Report a failure and exit if type checking fails

---

core/analyzer.go

It seems that the typechecker isn't considering the entire package
fileset in the current way that gas is processing projects. This leads
to cases where types that are defined in one file aren't known about
when gas is processing other files within that module.
A redesign is needed, this is a temporary fix to return to old
behaviour.
Related to #113

Temporarily disable typechecker fatal error

---

rules/tls.go
rules/tls_test.go

Having the server select the best available cipher suite, it is more secured than allowing the client to pick a weak cipher configuration.

Add a check for PreferServerCipherSuites flag of tls.Config

---

filelist.go
filelist_test.go
rules/blacklist_test.go
rules/nosec_test.go
rules/sql_test.go

The filelist test was non-deterministic and causing intermittent
failures due to ordering. This change will ensure that the file list
returns an ordered list of files in the String() method now.
Additionally there were a number of test cases that the sample code
was incorrect, or would not compile. These have also been corrected.

Correct bad test cases and intermitent failure

---

README.md
rulelist.go
rules/big.go
rules/big_test.go

The big.Int.Exp might lead to DoS attacks if is used with a modulus equal with zero.
More details: https://www.cryptologie.net/article/347/my-first-cve-o-common-vulnerabilities-and-exposures/

Add a rule which audits the use of math/big.Int.Exp function call

---

filelist.go
filelist_test.go
main.go

This is a fix for issue #124. The `skip` option is extended to support partial path match. Currently it is possible to exclude the vendor folder with this pattern only:
```
gas -skip "*vendor*" ./..
```
I extended the `fileList` to support also partial paths like this:
```
gas -skip vendor ./..
```

Add support for partial path match in the skip option

---

Dockerfile
README.md

This container can be built and run locally, in order to provide a simple way for users to run Gas on their code. The README has been updated to give information and provide build/run commands.

Adding Docker container and updating README

---

call_list.go
call_list_test.go
rules/bind.go
rules/rsa.go
rules/subproc.go
rules/tempfiles.go
rules/templates.go

By allowing partial matches of selectors there are chances of collisions
such as those in issue #145, this removes it to expect explicit packages
for each rule.
Closes #145

Use explicit packages in call lists

---

analyzer.go
analyzer_test.go
cmd/gas/main.go

This is much faster because the loader can reuse packages.

Do a single build for all packages

---

analyzer.go

This allows processing to continue to work around the loader issue identified in #159 .

[Issue 159] Allow loader errors so that processing continues

---

README.md
cmd/gas/main.go
output/formatter.go
output/junit_xml_format.go

This PR creates a new output format, namely: `JUnit XML` format, following [IBM's definition](https://www.ibm.com/support/knowledgecenter/en/SSQ2R2_9.5.0/com.ibm.rsar.analysis.codereview.cobol.doc/topics/cac_useresults_junit.html).
This allows the results generated by `gas` to be used by CI tools, like Jenkins, which are able to parse/read `JUnit XML` results in their various workflows.
Example command to output `JUnit XML`:
```
gas -exclude=G104 -fmt=junit-xml -out=report.xml ./...
```
This PR is in reference to #158.

JUnit XML output

---

output/junit_xml_format.go

`issue.Code` can contain `html` tags/characters, thus causing the parsing/reading of the JUnit XML output  in another component to fail.
Fixed by escaping `html` strings.

Escape html string for JUnit output

---

.travis.yml
README.md
rules/rulelist.go
rules/rules_test.go
rules/ssh.go
testutils/source.go

Add a rule to audit the usage of ssh.InsecureIgnoreHostKey

---

rules/errors.go

This is a rebase of [PR-147](https://github.com/GoASTScanner/gas/pull/147).

Add Fprint, Fprintf, Fprintln to NoErrorCheck whitelist

---

.travis.yml
cmd/gas/main.go
cmd/gas/sort_issues.go

Sort the issues by severity in descending order before creating the report. This will print the most critical issues at the top of the report. 
This is useful when doing security audit in large code bases with hundred of warnings. 
cc @gcmurphy

Sort the issues by severity in descending order

---

rules/fileperms.go

I would make the folder permissions a bit more permissive than `0700`. This is a bit too strict and it produces too many false positives. For instance, large projects such as Kubernetes has adopted `0750` as default permissions.
cc @gcmurphy

Make the folder permissions more permissive to avoid false positives

---

rules/tls.go

TypeOf returns the type of expression e, or nil if not found. We are
calling .String() on a value that may be nil in this clause.
Closes #174

Add nil pointer check to rule.

---

.github/issue_template.md

This patch adds a template for Issues opened against the
gas project. That way, minimum information is present to debug
the problem.
Signed-off-by: Eric Brown <browne@vmware.com>

Add an issue template to the project

---

rules/hardcoded_credentials.go

The current hardcoded credentials rule fails to handle #nosec comments in const decl blocks, like
```
const (
Token = "qw12r4jjwq1rdvsp" //#nosec
)
```
This change allows this to be handled by the existing analyzer ignore system.

Switch to valuespec instead of gendecl for hardcoded credential rule

---

README.md

This fixes a couple issues found in the README in the development
section:
* There was no information provided on dependencies.  Both go/dep
and golint are required to run make.
* To run the tests, the command 'make test' not 'make tests' has
to be used.

Fix up some mistakes in the README instructions

---

output/formatter.go

Since rule IDs are now available (#188), it would be nice for newbies to be able to see them in the default text output and correlate back to documentation.
Before:
```
[.../database.go:266] - Errors unhandled. (Confidence: HIGH, Severity: LOW)
> scope.SetColumn(x.DBName, encoded)
```
After:
```
[.../database.go:266] - G104: Errors unhandled. (Confidence: HIGH, Severity: LOW)
> scope.SetColumn(x.DBName, encoded)
```
This makes it easier to write annotations using `#nosec:RuleID` as well.

Add rule ID to default text output template

---

analyzer.go
cmd/gas/main.go

This change introduces the logic to resolve packages using gotool
and build packages from filepaths. It assumes that the packages
being scanned are located within the GOPATH.
If the GOPATH environment variable is not set the GOPATH is derived
as $HOME/go.
Relates to #184

Support package resolution and filepaths

---

cmd/gas/main.go

Discard the logs messages if the quite flag is set. 
Fixes #196 
cc @gcmurphy

Discard the logs messages if the quite flag is set

---

README.md
analyzer.go
analyzer_test.go
cmd/gas/main.go
rules/rules_test.go
testutils/source.go

Add an option to Go build tags (https://golang.org/pkg/go/build/)
@Fixes #157 
cc @gcmurphy

Add an option for Go build tags

---

.travis.yml
README.md
rules/archive.go
rules/rulelist.go
rules/rules_test.go
testutils/source.go

@gcmurphy I am giving a try to implement a rule which detects a potential path traversal when extracting zip archives. I would be happy to get your feedback. Thanks
Fixes #205

Rule which detects a potential path traversal when extracting zip archives

---

README.md

Extend the readme to document the ability to prevent some, but not all, rules from being enforced within an AST node. (Addresses the issue I opened at https://github.com/securego/gosec/issues/224)

Document #nosec use with a list of rules

---

helpers.go
rules/sql.go

This is a small update to the sql ruleset. `ConcatString` takes a binary expression and forms a string of all of its literals. In rules/sql.go, the function is used when evaluating format string vulnerabilities if the first argument in `fmt.Sprintf` is a binary expression. eg. `fmt.Sprintf("SELECT *" + " FROM foo" + " WHERE user='%s'", user)`

Small update to G201 and added ConcatString Function

---

helpers.go
rules/readfile.go
testutils/source.go

This update to rule G304 gives gosec the ability to evaluate two path joining functions as well as binary expressions when inside `ioutil.Readfile` or `os.Open`. Gosec can now flag cases like:
`ioutil.Readfile("/tmp/" + input + "/blob")` and `os.Open(filepath.Join("/tmp/", file))`. To do this, a new function called `FindVarIdentities` was added to helpers.go. The function will return all variable identities found in a binary expression.

update to G304 which adds binary expressions and file joining

---

README.md
cmd/tlsconfig/tlsconfig.go
rules/rulelist.go
rules/rules_test.go
rules/ssrf.go
testutils/source.go

This PR is implementing the SSRF rule from PR 189. I have many small changes and added the ability to look at the last selector in a Call expression and compare that to the selectors passed in from net/http. This will catch wrapped clients as well as other libraries exposing GET/POST/HEAD/PUT methods. One downside is that it cannot resolve that selector's originating type and therefore may flag false positives. The current way of resolving the url variable also leads to some false positives but I have some ideas to fix this later. 
Please let me know what you think.

G107 - SSRF

---

rules/ssrf.go
testutils/source.go

I removed the second check from G107 that looks just at the selectors based on issue 237. From my testing, it yielded just as many false positives as the other rules but I guess my testing wasn't broad enough. I want to add the go-resty library to G107 but I need to play around with `GetCallInfo` a little bit more. @ccojocar Sorry for the confusion.   
fixes #237

Removed wrapping feature from G107 (for now)

---

analyzer.go
resolve.go
rules/rules_test.go
rules/sql.go
testutils/source.go

Fixes #169. Sorry, it's been a while, was busy with work. 😅 
This PR aims to handle the following case:
main.go
```go
package main
func main() {
...
rows, err := db.Query("SELECT * FROM foo WHERE gender = " + gender)
...
}
```
constants.go (for example)
```go
package main
...
const gender = "M"
...
```
Currently, gosec will flag this this out as an issue in `main.go` as the `gender` identifier is unresolved. 
This PR will add `pkg.Files` to `gosec.context` so that we will be able to resolve that identifier if it happens to be in the global scope of that package.

Fix false positives for SQL string concatenation with constants from another file

---

Dockerfile

Update the golang in `Dockerfile` from 1.10 to latest 1.11.
Stuff still works:
```
$ make image
Building the Docker image...
docker build -t securego/gosec:1.1.0-12-g1ecd47e .
[+] Building 0.7s (13/13) FINISHED
=> [internal] load .dockerignore                                          0.0s
=> => transferring context: 2B                                            0.0s
=> [internal] load Dockerfile                                             0.0s
=> => transferring dockerfile: 38B                                        0.0s
=> [internal] load metadata for docker.io/library/golang:1.11.1-alpine3.  0.6s
=> [internal] load build context                                          0.0s
=> => transferring context: 15.52kB                                       0.0s
=> [stage-1 1/3] FROM …
```

bump Dockerfile golang from 1.10 to 1.11

---

analyzer.go
analyzer_test.go
cmd/gosec/main.go
config.go
config_test.go
rules/errors.go
rules/rules_test.go
testutils/source.go

Detect the unhandled errors even though they are explicitly ignored if the 'audit: enabled' setting is defined in the global configuration

---

README.md

1. Example config json included a trailing comma, even though as we obviously know this is how things should be, JSON does not agree and the parser fails miserably
2. Flag was incorrectly stated as -config in the README, the correct flag is -conf
3. Example command did not work as did not include final dot to examine the current pkg.

Fix -conf example in README.md

---

cmd/gosec/main.go

This PR's goal is to add a `no-fail` flag to avoid the scanning to fail. This can be very useful in CIs and way cleaner than doing `gosec ./... || true`.

Add a no-fail flag

---

testutils/pkg.go

The tests assumed to had GOPATH set. 
Simple fix really.
BTW there seems to be a failing test in `master`.

revert to default GOPATH if necessary

---

testutils/source.go

I thought that an example where the user inputs a URL is more realistic.
Because if your operating system is already hacked then you are already screwed.

Change test

---

analyzer.go
analyzer_test.go
cmd/gosec/main.go
errors.go
output/formatter.go
rules/rules_test.go

Right now if you use Gosec to scan invalid go file and if you report the result in a text, JSON, CSV or another file format you will always receive 0 issues.
The reason for that is that Gosec can't parse the AST of invalid go files and thus will not report anything.
The real problem here is that the user will never know about the issue if he generates the output in a file.
I fix this problem in this patch and I added those Golang errors in the output.
Now when there are Golang errors found Gosec will exit with code 1.

Report for Golang errors

---

cmd/gosec/main.go

Reading https://github.com/securego/gosec/pull/284 , I think this is a good idea, but I do not think we should fail if there were errors if the no-fail flag is present.
It's great that it errors are added to the output, but someone using the no-fail flag will likely be looking at the output anyway. So failing is not necessary / logic.
I found that while I was trying to follow a fail issue that I first thought was related to cgo imports (https://github.com/securego/gosec/issues/289) but actually was due to this `no-fail` logic change

fix no-fail flag logic

---

README.md
cmd/gosec/main.go
output/formatter.go
output/sonarqube_format.go

Add sonarqube output

---

analyzer.go
analyzer_test.go

This avoids loading all packages in memory before running the checks.
fixes #303 #305

Refactor the analyzer to process one package at the time

---

cmd/gosec/main.go

We validate that a proper installation was done by printing version string and exit with code 0.
Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

print version string

---

README.md

Currently, if you download the gosec binary using the commands
suggested in the README and you decide to check the checksum
of the binary, you just downloaded then your checksum check will fail.
As a result, the user can think that your binary is corrupted.
The reason for that failure is that the checksums are for the
tar.gz files provided in the release notes.
This should be documented to avoid future unclarities.

Add checksum clarification in the README

---

cmd/gosec/main.go

This takes into account the filtered number of issues instead of
the total number. This number is more relevant to developers, as
the intention was to not take certain issues into account anyway.
Closes #331

Display filtered number of issues instead of total in stats

---

output/formatter.go
output/formatter_test.go

The json encoding of uninitialized arrays is `null`. This causes a NPE in sonarqube tool. We should return an empty array rather than a null value here.
Example of this behaviour is: https://play.golang.org/p/UUvP9JwsYlm
Relates to: #333

Prevent null pointer exception in Sonarqube

---

analyzer.go
analyzer_test.go
cmd/gosec/main.go
config.go

This PR aims to add a new flag to Gosec that allows users to change the directive for ignoring vulnerabilities.
* `analyzer.go`: Add logic to check if the default directive has changed.
* `analyzer_test.go`: Add test cases to cover the addition.
* `cmd/gosec/main.go`: Add `nosec-tag` flag.
* `config.go`: Creates a new global variable, `NoSecAlternative `, to hold the directive for ignoring vulnerabilities.

Add flag to handle '#nosec' alternative

---

README.md

Go modules requires that the tag starts with a `v`.
fixes #347

Update the tag format in the release steps

---

testutils/source.go

The existing unit tests for G107 didn't have any comments why
a certain code is problematic.
Other than that we need more unit tests for rule G107 for the
different scenarios.

Clarify and add new unit tests for rule G107

---

testutils/source.go

The unit tests should check for a single thing at a time.
This was not true for some the tests.

Change unit tests to check for one thing

---

renovate.json

I *think* this schedule only monthly semver updates but still give us
vulnerability alerts.
See: https://docs.renovatebot.com/presets for more information.

reconfigure renovatebot

---

go.sum
resolve.go
resolve_test.go
rules/ssrf.go
testutils/source.go

Made also the rule to not report an issue when encountering function scoped
variable which terminate in a basic literal such as a string.
fixes #379

Improve the SSRF rule to report an issue for package scoped variables

---

issue.go
issue_test.go
output/formatter.go
output/formatter_test.go
output/junit_xml_format.go
output/sonarqube_format.go

Fixes #368
Add CWE rule mappings to gosec rules.

Julian add cwe rulemappings

---

Dockerfile

The docker image doesn't include the necessary packages to build / analyze
some packages. Adding gcc and libc-dev to address this.
Fixes #420

fix(docker) gcc and libc-dev needed for bindings

---

README.md
cmd/gosec/main.go
issue.go
issue_test.go
output/formatter.go
output/formatter_test.go

- Add new output format (same format as golint)
- As written in issues below, golint is a very common lint tool for Go, So it's easy to integrate with other tools if gosec has this format.
Fixes https://github.com/securego/gosec/issues/423 https://github.com/securego/gosec/issues/424

Add golint format to output format

---

README.md
analyzer.go
issue.go
output/formatter_test.go
rules/integer_overflow.go
rules/rulelist.go
rules/rules_test.go
testutils/pkg.go
testutils/source.go

- Add rule to detect potential integer overflow 
* (this is my first PR for gosec.)
- strconv.Atoi may cause Integer Overflow. But gosec doesn't check this. So I would like to add this rule.
- Details
- In a third-party security audit of the Kubernetes project, many potential integer overflow bugs were found. So I think this bug is common and should be detected by gosec.
- Kubernetes Audit Report
- P93 ("B. strconv.Atoi result conversion may cause integer overflows")
- https://github.com/kubernetes/community/blob/master/wg-security-audit/findings/Kubernetes%20Final%20Report.pdf
- As written in the report, developer should use strconv.ParseInt or strconv.ParseUint to parse string
- This rule checks code by every ast.FuncDecl (by Function)
- This rule has to check multiple expressions in …

Add a rule which detects when there is potential integer overflow

---

analyzer.go
analyzer_test.go
testutils/source.go

A Cgo file seems to be expanded into 3 different files by the package loader 
which doesn't map to the original Cgo file. This files are only stored in the 
cached without a go extension. For now is safe bet to just ignore them to 
avoid false warnings which doesn't related directly to the original Cgo file. 
I haven't managed to find a way to get the AST of a Cgo file such that it can 
be reliably analysed.
related #408

Add the Cgo files to the analysed files and ignore all non-Go files

---

README.md
issue.go
output/formatter_test.go
rules/decompression-bomb.go
rules/rulelist.go
rules/rules_test.go
testutils/source.go

- Add rule to detect potential DoS vulnerability via decompression bomb
- io.Copy may cause Denial of Service. It's better to use io.CopyN instead of io.Copy when decompression.
- This rule detects io.Copy when decompression only.
- Details
- In a third-party security audit of the Prometheus and Open Policy Agent, potential DoS vulnerabilities were found via io.Copy. This rule can detect these bugs.
- Ref: https://cure53.de/pentest-report_opa.pdf
- P11: Server: Denial of Service via GZip bomb in bundles
- Ref: https://prometheus.io/assets/downloads/2018-06-11--cure53_security_audit.pdf 
- P13: Clients can cause Denial of Service via Gzip Bomb
1. To catch ident for *archive/zip.File.Open, I use containsReaderCall func
1. To compare ident, I use *ast.Ident as the key(This is a different …

Add a rule which detects potential DoS vulnerability via decompression bomb

---

rules/integer_overflow.go
testutils/source.go

Modify G109(Potential Integer overflow) to use *ast.Object as key.
- ident's name(string) was used to check whether the value is used by strconv.Atoi or not.
- I changed the key from ident's name to *Object.
- It seems the same name in the same function wasn't distinguished before, even if it is different ident. But this change can recognize same ident more accurately because the same ident has the same *ast.Object.
- "value" in "main()" and "if" are different variables.
- But current rule detects this code
- my change doesn't detect this code
```go
func main() {
value := 10
if value == 10 {
value, _ := strconv.Atoi("2147483648")
fmt.Println(value)
}
v := int32(value)
fmt.Println(v)
}
```

Modify rule for integer overflow to have more acurate results

---

README.md
cmd/tlsconfig/tlsconfig.go
rules/fileperms.go
rules/rulelist.go
rules/rules_test.go
testutils/pkg.go
testutils/source.go

`io/ioutil`'s `WriteFile` will create a file if one does not exist.  This PR adds a rule for checking whether the permissions of the file exceed a value (default `0600`).
Please let me know if I can make any changes (will squash and rename before merge).

Add a check for `WriteFile` permissions.

---

README.md
cmd/gosec/main.go
rules/bad_defer.go
rules/rulelist.go
rules/rules_test.go
testutils/source.go

This adds a rule for `defer`ing the call to a function which returns an error which should be checked. 
I've used a mostly arbitrary rule label `G307`.  
Please let me know what changes can/should be made if this is desired upstream.

Detecting unsafe `defer` of `os.File.Close()`

---

rules/subproc.go
testutils/source.go

Improve the subproc rule to handle CommandContext, syscall.ForkExec and syscall.StartProces

---

cmd/gosec/main.go
go.mod
go.sum
issue.go
issue_test.go
output/formatter.go
output/formatter_test.go

Add a flag `-color` to support colored output. This is only available for text output format.
Using the [gookit/color](https://github.com/gookit/color) to have support for a range of OS.
It's not allowed to use that flag with other format types
The `Summary` and `Issues` sections are presented colored
The file path is presented colored and also the `Issues` number is red when it's more than zero
Running full example using different apps
closes #456

feature(formatter/text): Add color option on text format

---

.github/FUNDING.yml

Enable the funding button in the project following https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

Display a sponsor button in the repository

---

analyzer_test.go
rules/implicit_aliasing.go
testutils/source.go

In some cases the object reference can be nil. This makes sure we explicitly check for that.
fixes: #475

Add null pointer check in G601

---

analyzer.go

Based on this issue: #393 (comment)
BuildTags are propagated as BuildFlags. Tested with the provided code examples (#393).
fixes #393

Bug fix 393 - BuildTags are propagated

---

cmd/gosec/main.go
cmd/gosec/version.go

Make sure some version information is set when no version was injected into the binary

---

cmd/gosec/version.go

Fix panic when reading the version from debug info in Go 1.13

---

README.md
rules/blacklist.go
rules/rulelist.go
rules/rules_test.go
rules/weakcrypto.go
testutils/source.go

This PR changes naming from `blacklist` to `blocklist`.
some codes are changed by formatter. (e.g. trailing spaces)

Change naming rule from blacklist to blocklist

---

Dockerfile
entrypoint.sh

The GitHub action provide the arguments as a single string to the docker container,
so we need to expand them in order for gosec to properly interpret them.
This allows us to run a scan in a container and provide the arguments either:
```
docker run -it --rm -v <path-out>:<path-in> -w <path-in> securego/gosec -fmt=json ./...
```
or (which it happens in the case of GitHub action execution)
```
docker run -it --rm -v <path-out>:<path-in> -w <path-in> securego/gosec "-fmt=json ./..."
```
fixes #502

Expand the arguments to a list of strings when they are provided as a single string

---

issue.go
output/formatter.go
output/formatter_test.go

fixes #268
This will capture 3 lines around the place where the issue occurs. The output looks something like:
```
[/Users/cosmin/go/src/github.com/securego/gosec/issue.go:180] - G307 (CWE-703): Deferring unsafe method "Close" on type "*os.File" (Confidence: HIGH, Severity: MEDIUM)
179:        if file, err := os.Open(fobj.Name()); err == nil {
> 180:                defer file.Close()
181:                s := codeSnippetStartLine(node, fobj)
Summary:
Files: 50
Lines: 8069
Nosec: 21
Issues: 1
```
Also it marks properly a multiline finding:
```
[/Users/cosmin/go/src/github.com/securego/gosec/issue.go:170-171] - G102 (CWE-200): Binds to all network interfaces (Confidence: HIGH, Severity: MEDIUM)
169: func multiline() {
> 170:        _, _ = net.Listen("tcp",
> 171: …
```

Extend the code snippet included in the issue and refactored how the code snippet is printed

---

README.md
rules/archive.go
testutils/source.go

Hey `gosec` folks! great work with this tool :) 
I've tested rule G305 against packages with known vulnerabilities, and some of them were not detected. Contributing the following to rule G305:
1. `path.Join` could be used instead of `filepath.Join`. Making sure these occurrences get detected
2. `tar` files are susceptible to path traversals, including them
PS: I didn't create a new rule for .tar files since it will be just a replica of G305 with one line differing. Happy to move it to a different rule if this makes more sense to you.

feat: adds support for path.Join usage and tar archives in G305

---

rules/readfile.go
testutils/source.go

Fix the rule G304 to handle the case when the input is cleaned as a variable assignment

---

Makefile
README.md

The current working directory needs to be specified in the docker run
options in order for gosec to download the dependencies defined in the go
module file.
fixes #517

Update README file with some more details required to run successfully a scan with the docker image

---

cmd/gosec/sort_issues.go
cmd/gosec/sort_issues_test.go
go.mod
go.sum
output/formatter.go
output/formatter_test.go
output/junit_xml_format.go

In some cases, stable ordering or the reproducible output is needed(CI).
This PR adds additional sorting to severity sorting to ensure stable output.
Futhermore this also fix junit output which didn't respect ordering.

Reproducible junit report

---

cmd/gosec/main.go
output/formatter.go
output/formatter_test.go
output/sarif_format.go

This pull request supports the [SARIF](https://docs.oasis-open.org/sarif/sarif/v2.0/csprd02/sarif-v2.0-csprd02.html) output option.
SARIF is also supported on GitHub Code Scanning. Upload the resulting report to GitHub so you can view your audit on GitHub. More details [here](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/integrating-with-code-scanning).
The SARIF report generated by `gosec -fmt=sarif ...` has the following format:
<details>
<summary>details</summary>
```json
{
"$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.4.json",
"version": "2.1.0",
"runs": [
{
"tool": {
"driver": {
"name": "gosec",
"informationUri": "https://github.com/securego/gosec/",
"rules": [
{
"id": "G401 (CWE-326)", …
```

Support SARIF output

---

call_list.go

The extra space causes that line to be in block quotes rather than normal text: https://godoc.org/github.com/securego/gosec#CallList.ContainsPkgCallExpr

fix typo in ContainsPkgCallExpr comment

---

rules/rules_test.go
testutils/pkg.go
testutils/source.go

This partially addresses #549. I fixed what seemed like typos to me, but there are still three failing specs that I'm not equipped to address:
1. `[Fail] gosec rules report correct errors for all samples [It] should detect pprof endpoint`
The failing sample was introduced in 29341f6e. It seems to assert that importing `net/http/pprof` without an alias disables rule G108 when using `http.DefaultServeMux`. Is that the correct behavior?
```
sample_1_0.go:8:2: "net/http/pprof" imported but not used
```
2. `[Fail] gosec rules report correct errors for all samples [It] should detect file path provided as taint input`
The failing sample was introduced in f13b8bc6. It seems to assert that using `filepath.Rel` sanitizes path input, but that function returns an error. How should that error affect …

Assert that sample code compiles

---

output/sarif_format.go

Fixes #556.
I copied over the code from the Sonarqube formatter and swapped out the `strconv.Atoi` for a `strconv.ParseUint` because that's what the existing code did - it's worth noting that the rest of the code in `gosec` uses `strconv.Atoi`.

Fix for SARIF output when Issue.Line contains a range

---

output/formatter.go

Currently master is returning a `null` result when there are none returned, this doesn't match the JSON schema.
```json
{
"$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.4.json",
"version": "2.1.0",
"runs": [
{
"tool": {
"driver": {
"name": "gosec",
"informationUri": "https://github.com/securego/gosec/"
}
},
"results": null
}
]
}
```
The schema specifies results must be empty not null as below.
```json
"results": {
"description": "An array of result objects that will be merged with a separate run.",
"type": "array",
"minItems": 0,
"uniqueItems": false,
"default": [],
"items": {
"$ref": "#/definitions/result"
}
},
```

Fix for sarif output, the results are an empty array if nothing is reported

---

output/sarif_format.go

i have been working on getting a good example of integration with the GitHub security scanning, which required a bit of research into how SARIF is processed by this service. One of the issues I have had is the checks seemed to default to warning so it wouldn't mark the PR as failed, this was resolved with the addition of a level on the rule.
For reference I got a hint about this information from https://github.com/hunt3rkillerz/Snyk-To-Sarif-JS/blob/main/snyk-to-sarif.js#L161-L163

fix sarif add default configuration set to correct level

---

README.md

As requested I have put together some instructions on how to get `gosec` integrated with GitHub Code Scanning feature.
This will however require a release of `gosec` which will in turn update the GitHub Action described below.
I can't this workflow fully till this release happens :joy:

update README with instructions on how to integrate with GitHub codescanning

---

output/formatter.go
output/sarif_format.go

closes #563 
PR attempts to fix issues formatting issues with produced SARIF report.
Covered changes:
1. Use running tip version of the SARIF `$schema`
2. `tool` declares it's version. Used the same version as the `$schema`, might not be ideal but that fixes the immediate problem of invalid SARIF schema. The other option could be passing through commit SHA or gosec module version.
3. `tool`'s `rules` couldn't be duplicated
4. `results`' `locations` array should have only a single entry (https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317650).

Fix sarif formatting issues

---

go.sum
rules/tls.go
testutils/source.go

Reset the state of TLS rule after each version check

---

README.md

Update README with a note which describes how to import a SonarQube report

---

rules/fileperms.go

In go 1.16 the `ioutil` package was deprecated and
the functions should be replaced by their equivalents
in either `io` or `os` packages. This means,
that `ioutil.WriteFile` should be replaced by
`os.WriteFile` instead. To account for this change
and to detect incorrect permissions also for `os.WriteFile`
I changed `filePermissions` rule slightly to allows
specifying multiple packages that can contain given
function and that we should check. This workaround
can be removed after a sufficient time has passed
and after it is decided that checking `os.WriteFile`
is enough.
Fixes: https://github.com/securego/gosec/issues/576

fix: WriteParams rule to work also with golang 1.16

---

rules/tls.go

The TLS config rules have always been `int16` while the upstream `tls.Config` type has always been `uint16`. The `tls` version constants are untyped.
LGTM.com ([CodeQL](https://securitylab.github.com/tools/codeql)) warns
> Incorrect conversion of a 64-bit integer from `strconv.ParseInt` to a lower bit size type int16 without an upper bound check.

Quiet warnings about integer truncation

---

README.md
cmd/gosec/main.go

This PR adds up the `-stdout` flag to enable the results to be reported to stdout (console log) and at the same time it'll get stored inside the file provided by `-out` flag. 
It adds the `-verbose` flag to choose which format the stdout should follow while output format is present.
This helps in Devops CICD pipelines to store the generated report as an artifact and at the same time, makes it easily available in logs. 
fixes #600

ISSUE-600 | Adding -stdout -verbose Flag

---

report/html/template.go

This PR adds the number of waived nosec false positives to the stats section of the html report.
If I have waived findings in the code I'd like to see how many of them I have in the stats.

show nosec in html report summary

---

rules/errors.go

go/src/hash/hash.go:
...
type Hash interface {
// Write (via the embedded io.Writer interface) adds more data to the running hash.
// It never returns an error.
io.Writer
...

errors.go: add Hash.Write() to the white list.

---

.github/workflows/scan.yml

This will prevent issues on security scan like #649 to be discovered by others

Add security scan

---

.github/workflows/release.yml

To avoid breaking the build when cyclonedx-gomod introduces breaking changes in a new major version. See https://github.com/CycloneDX/gh-gomod-generate-sbom/releases/tag/v0.3.0

Use version `^v0` instead of `latest` for cyclonedx-gomod

---

rules/tls.go
testutils/source.go

Fix for #528
This PR update the assignment checking for `MinVersion` of TLS

fix: add variable assignment checking as part of MinVersion

---

Makefile

PR to address ticket https://github.com/securego/gosec/issues/664 for populating correctly the version information when building `gosec` 
fixes #644

fix: BUILDFLAGS updated with correct versions information

---

.gitignore
helpers.go
helpers_test.go

This PR allows the exclude-dir option to exclude subdirs.
This allows to define the exclude rules more precisely.

support subdir in exclude-dir

---

analyzer.go
analyzer_test.go
cmd/gosec/main.go
config.go
issue.go
report/html/template.go
report/text/template.go
report/text/writer.go

Our Security regulations demand evidence reports that our source code follows secure coding guidelines.
We are using gosec for this purpose.
The regulations demand, that waived issues are also listed. Hence it would be great, if gosec optionally could generate reports, where waived issues are reported, but not counted as such and marked as waived.
This PR implements a possible solution but fails to get valid unittests. 
As suggested by @ccojocar in https://github.com/securego/gosec/issues/675 I open it as a PR.
fixes #675

Add possibility to list waived (nosec) marked issues but not count them as such

---

report/html/template.go

The code segment in the issues list was not updated due to a missing component key.
This PR fixes this.

add key to Highlight component

---

cmd/gosec/main.go
cmd/validate/flag.go
cmd/vflag/flag.go
flag_test.go

Fix: #535 
Create a separate type to allow CLI validation using the `flag` package from the go library.

fix: create a separate type for flag that has validation

---

Dockerfile

I'm trying to scan a project which has dependencies which are private projects. When Go tries to fetch the dependencies it normally uses HTTPS, but that doesn't work if they're private (terminal prompts disabled, can't enter username/password). So you do this little trick with git configuration to get Go to fetch dependencies over ssh: `GIT_CONFIG_PARAMETERS=url.ssh://git@github.com/.insteadOf=https://github.com/`
unfortunately the docker image doesn't have ssh installed so this doesn't work :)

add openssh to docker image

---

report/html/template.html
report/html/writer.go
report/text/template.txt
report/text/writer.go

Since go 1.15 is now phased out we could reactivate the changes from https://github.com/securego/gosec/pull/625
Use go embed feature to make template maintenance easier.

use go embed for templates

---

rules/subproc.go

Fix a panic in suproc rule when the declaration of the variable is not available in the AST

---

README.md
analyzer_test.go
cmd/gosec/main.go
cmd/gosecutil/tools.go
cmd/tlsconfig/tlsconfig.go
issue.go
testutils/pkg.go
testutils/source.go

Comments intended for machines to read do not have the space by convention.
I'm unable to find an "authoritative" reference at the moment, but it is mentioned here and there, and is in my experience the convention indeed. Anyway one example mention is at end of https://golangci-lint.run/usage/false-positives/#nolint

Remove space between `//` and `#nosec` in examples and internal use

---

analyzer.go
analyzer_test.go

For this piece of code
```go
package main
import "fmt"
// #nosec -- j1
func main() {
username := "admin"
/* #nosec G101 -- j2 */
password := "f62e5bcda4fae4f82370da0c6f20697b8f8447ef"
fmt.Println("Doing something with: ", username, password)
}
```
If we run `gosec -fmt=sarif -track-suppressions ./...` on it...
Expected:
```
"suppressions": [
{ "kind": "inSource", "justification": "j1" },
{ "kind": "inSource", "justification": "j2" }
]
```
Actual:
```
"suppressions": [
{ "kind": "inSource", "justification": "j1" }
]
```
If gosec ignores all rules, it will skip checking specific rules.
Check both general suppressions and specific rule suppressions, then merge then together.

Track both #nosec and #nosec rulelist for one violation

---

analyzer.go

Handle nil when looking up a file by position into a package

---

Makefile

When `/bin/sh` is not a shell having `[[`, `make fmt` fails:
```
FORMATTING
/bin/sh: 1: [[: not found
```

build(fmt): use `[` instead of `[[`

---

rules/tempfiles.go
testutils/source.go

Find G303 with filepath.Join'd temp dirs

---

rules/sql.go
testutils/source.go

Problem
fixes #713
Details :
can be seen in #713.
G201 regexp only match callexpr once.
If there is a sqlquery like the following, there will be problems with matching.
func main() {
var name string
db, err := sql.Open("sqlite3", ":memory:")
if err != nil {
panic(err)
}
q := fmt.Sprintf("SELECT name FROM users where id = '%s'", os.Args[1])
err = db.QueryRow(q).Scan(&name)
if err != nil {
panic(err)
}
defer db.Close()
}
Solution
Add an extra check befor checkQuery.

Fix false negative for SQL injection when using DB.QueryRow.Scan()

---

cmd/gosec/main.go
rules/readfile.go
testutils/source.go

Add os.Create to the readfile rule

---

rules/sql.go
testutils/source.go

fixes #756
can be seen in #756.
G201,G202  only match  Query, QueryContext, QueryRow, QueryRowContext .
If there is a SQLStr like the following, there will be problems with matching.
```
db.Exec("SELECT " + cols + " FROM DUAL")
```
Add `Exec`, `ExecContext`, `Prepare` and `PrepareContext`.

Add db.Exec and db.Prepare to the sql rule

---

rules/tls.go
testutils/source.go

- Add a test for tls min version defined in a different file
- Resolve the TLS min version when is declarted in the same package but in a different file
fixes #767

Fix TLS min version resolution when is defined in the same package but in a different file

---

README.md

- Because of rebranding (Daimler AG has become
Mercedes-Benz Group AG) the github organization has
been renamed as well.
- Updated sponsorship link in README.md to new github organization

Updated sponsor link in README.md

---

report/sarif/formatter.go
report/sarif/sarif_test.go

Preprocess the code snippet from the issue in order to extract only the line(s)
of code where the issue is located.  In addition remove the line numbers and whitespaces
before writing the code snippet into the SARIF report.
fixes #773

Process the code snippet before adding it to the SARIF report

---

analyzer.go
analyzer_test.go
cmd/gosec/main.go
rules/rules_test.go

This PR adds support for running package loading in parallel due to `gosec.load` being a major bottleneck for big projects. 
The concurrency option defaults to the number of available CPUs and tests are using a concurrency value of 1.
Benchmarks of a couple of GitLab projects using [hyperfine](https://github.com/sharkdp/hyperfine/):
___
```
Benchmark 1: /path/to/gosec -exclude-generated ./...
Time (mean ± σ):     11.384 s ±  0.227 s    [User: 28.443 s, System: 8.731 s]
Range (min … max):   10.974 s … 11.793 s    10 runs
Warning: Ignoring non-zero exit code.
```
```
Benchmark 1: /path/to/gosec -exclude-generated ./...
Time (mean ± σ):      2.292 s ±  0.078 s    [User: 23.965 s, System: 8.732 s]
Range (min … max):    2.230 s …  2.469 s    10 runs
Warning: Ignoring non-zero exit code.
``` …

feat: add concurrency option to parallelize package loading

---

go.mod
go.sum

This change bumps the version of `golang.org/x/tools` to pick up a fix for golang/go#51629.

Update x/tools to pick up fix for golang/go#51629

---

README.md
call_list.go
helpers.go
issue.go
report/formatter_test.go
rules/math_big_rat.go
rules/rulelist.go
rules/rules_test.go
testutils/source.go

Rat.SetString in math/big in Go before 1.16.14 and 1.17.x before 1.17.7
has an overflow that can lead to Uncontrolled Memory Consumption.
It is the CVE-2022-23772.
Fix of #810

Add check for usage of Rat.SetString in math/big with an overflow error

---

.github/workflows/release.yml

We now have tags available in the cosign-installer, which allows us to pin the latest release via `v2`.

Pin cosign-installer to `v2`

---

rules/integer_overflow.go
testutils/source.go

Fix #742 : G109 tells the location at strconv.Atoi instead of strconv.Atoi result conversion to int16/32. 
Before this commit, G109 will report on `strconv.Atoi`.
After this, it will report on the convertion like`int32(a)`.

Fix wrong location for G109

---

cmd/gosec/main.go

This fix addresses an issue where the default exclude aimed to exclude `.git` folders is erroneously excluding any file paths with `git` in them.
For example, given a path like `src/git-client/main.go` or `client-git/main.go` the current implementation fails to scan that directory. This causes `gosec` to error with `No packages found` when a folder being scanned only contains `.go` files in these erroneously matched paths.
I verified this by using regexpal.com and the strings `src/git-client/main.go` and `client-git/main.go` mentioned above. The existing exclude `.git` compiles to `([\\/])?.git([\\/])?` which causes the problem as the `.` isnt escaped. The fixed `\\.git/` compiles to `([\\/])?\.git\/([\\/])?` which escapes the leading `.` and adds the protection of the required trailing …

fix: filepaths with git anywhere in them being erroneously excluded

---

.github/workflows/ci.yml

Phase out support for Go 1.16 since is not supported anymore by Go team

---

helpers.go
rules/tls.go
testutils/source.go

This PR fixes https://github.com/securego/gosec/issues/820 issue
This PR contains several changes
1. Check package path instead of package name. 
Comparing by package path is more trustful than comparing by package name. It's the only source of truth(after resolving the aliases) to check what exactly package was imported(=accessed in our case).
2. Move "unaliasing" from GetImportedName to GetImportPath
It will help us to get exact information about imported package.

Fix for G402. Check package path instead of package name

---

rules/sql.go

Remove hardwired assumption and heuristics on index of arg taking a SQL string, be explicit about it instead.
Originally part of https://github.com/securego/gosec/pull/834, see discussion on details in it.

Refactor SQL rules for better extensibility

---

cmd/gosec/main.go
helpers.go

The parsing of the Go version inside the function `GoVersion` is based on an incorrect assumption.
https://github.com/securego/gosec/blob/0c8e63ed86f8fc2da42787e0a653114490078d6c/helpers.go#L476-L482
The Go version follows a specific pattern.
- go1.19rc2
- go1.19beta2
- go1.19.4
- go1.19
The current version of Go is `go1.19` then `versionParts[2]` panic (`runtime error: index out of range [2] with length 2`)
Fixes #843
The problem has been introduced by #819
Related to https://github.com/golangci/golangci-lint/issues/3071

fix: parsing of the Go version

---

helpers.go
testutils/source.go

- fixes https://github.com/securego/gosec/issues/862
- relates to https://github.com/securego/gosec/issues/820
- relates to https://github.com/securego/gosec/pull/838
It appears that `GetImportedName` returns _both_ aliased and non-aliased imports.
As a result, a file having both crypto/rand and math/rand (but aliased) would
trigger false positives on G404. Given the following file;
```go
package main
import (
"crypto/rand"
"math/big"
rnd "math/rand"
)
func main() {
_, _ = rand.Int(rand.Reader, big.NewInt(int64(2)))
_ = rnd.Intn(2)
}
```
And patching for debugging;
```patch
diff --git a/helpers.go b/helpers.go
index 437d032..80f4233 100644
--- a/helpers.go
+++ b/helpers.go
@@ -250,6 +250,8 @@ func GetBinaryExprOperands(be *ast.BinaryExpr) []ast.Node {
// GetImportedName returns the name …
```

Fix false positives for G404 with aliased packages

---

entrypoint.sh

Would be great to have something like this inside the Docker image for working with private repositories.
Especially when running local and there's no other way than vendoring at the moment.

Add a way to use private repositories on GitHub

---

analyzer.go
helpers.go
import_tracker.go
import_tracker_test.go
testutils/source.go

The existing code assumed imports to be either imported, or imported with an
alias. Badly formatted files may have duplicate imports for a package, using
different aliases.
This patch refactors the code, and;
Introduces a new `GetImportedNames` function, which returns all name(s) and
aliase(s) for a package, which effectively combines `GetAliasedName` and
`GetImportedName`, but adding support for duplicate imports.
The old `GetAliasedName` and `GetImportedName` functions have been rewritten to
use the new function and marked deprecated, but could be removed if there are no
external consumers.
With this patch, the linter is able to detect issues in files such as;
package main
import (
crand "crypto/rand"
"math/big"
"math/rand"
rand2 "math/rand"
rand3 "math/rand"
)
func main() {
_, _ = …

Refactor to support duplicate imports with different aliases

---

cmd/tlsconfig/tlsconfig.go
rules/bad_defer.go
testutils/source.go

Simply adds some additional type for bad-close check.
Will fix https://github.com/securego/gosec/issues/890 but maybe we need to redesign the check in future to catch possible cases(Close() method with error ret value)

Additional types for bad defer check

---

.goreleaser.yml

- Updated .goreleaser.yaml to support Linux on IBM Z ( s390x )
Signed-off-by: Dave Hay <david_hay@uk.ibm.com>

Adding s390x support

---

rules/tls.go

From [strconv.ParseInt](https://pkg.go.dev/strconv#ParseInt):
> If the base argument is 0, the true base is implied by the string's prefix following the sign (if present): 2 for "0b", 8 for "0" or "0o", 16 for "0x", and 10 otherwise. Also, for argument base 0 only, underscore characters are permitted as defined by the Go syntax for [integer literals](https://go.dev/ref/spec#Integer_literals).
This is useful for example for hex constants from the [crypto/tls](https://cs.opensource.google/go/go/+/master:src/crypto/tls/common.go;l=32), e.g.:
```
VersionTLS13 = 0x0304
```
PS. Codepath in the `MinVersion` parsing looks quite fragile.
PPS. Code in Min/Max should likely be the same.

Auto-detect TLS MinVersion integer base

---

install.sh

Fix CI installation using `install.sh`.
https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-a-release-by-tag-name

fix github release url

---

install.sh

Fix install.sh. on empty tag.
latest release url: https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-the-latest-release
error message
```sh
Run curl -sSfL https://raw.githubusercontent.com/securego/gosec/master/install.sh |
curl -sSfL https://raw.githubusercontent.com/securego/gosec/master/install.sh |
sh -s -- -b $GOPATH/bin
shell: /usr/bin/bash -e {0}
env:
GOPRIVATE: github.com/Kyash/*
GOPATH: /home/runner/go
securego/gosec info checking GitHub for latest tag
securego/gosec crit unable to find '' - use 'latest' or see https://github.com/securego/gosec/releases for details
Error: Process completed with exit code 1.
```

Fix regression of github latest URL

---

rules/hardcoded_credentials.go
testutils/source.go

fix: adaper equal expr which const value at left.
```
if "Tr0ub4dour_UPL&&LOlo" == pwd
```

Update hardcoded_credentials.go fix: adaper equal expr which const value at left

---

.github/workflows/ci.yml
.github/workflows/release.yml
Makefile
analyzer_test.go
report/html/writer.go

- Fix unit tests for Go 1.20
- Update to Go 1.20 in the build scripts

Update to Go 1.20 and fix unit tests

---

.github/workflows/release.yml

- Remove deprecated goreleaser flag from release build script
- Update cosign version to v1.13.1

Update release build script

---

.github/workflows/ci.yml
README.md
action.yml

- Add gosec version as a paramter to the Github action
- Run gosec as a github action as part of CI
fixes #926

Add gosec version as an input parameter to GitHub action

---

.golangci.yml

Increase timeout to 5 minutes and remove deprecated linters.
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

fix linting job

---

.github/workflows/release.yml

Use image digest instead of tag when signing the released image with cosign

---

analyzer.go
analyzer_test.go
config.go

The no-sec alternative tag prepends now automatically the # symbol
fixes #961

Fix no-sec alternative tag

---

analyzer.go
analyzers/ssrf.go
analyzers/util.go
cmd/gosec/main.go
helpers.go
helpers_test.go
report/formatter_test.go
report/sarif/sarif_test.go
report/sonar/sonar_test.go
rule.go
rules/subproc.go
testutils/source.go

This PR corrects spellings in comments, variable names, and test cases.

Fix typos in comments, vars and tests

---

.golangci.yml

It seems that it flags some imports which are part of the project.

Remove the depguard from the list of enabled linters

---

rules/hardcoded_credentials.go
rules/rules_test.go
testutils/source.go

I updated the HardcodedCredentials code to apply regex against the actual values themselves in assignment statements, valuespecs, and equalities.  The intention is to search for secrets, such as API keys, by looking for the values. For example if we have:
`key = "3490b39bc66f7e7730e8fa68041da2e4f7c0a6a8cb119466c3ddc5245bda1781"`
this would previously not be caught by gosec, because gosec only looks at the variable names. 
Now, with these changes, the code matches values too using a new regex pattern that will look for secrets such as this. I added a new config variable called "patternValue," with a default regex which searches for VirusTotal API keys (or other keys with the same format).

Feature: G101 match variable values and names

---

issue/issue.go
rules/rulelist.go
rules/rules_test.go
rules/slice_bounds.go
testutils/source.go

This PR addresses this issue: #954 
This adds a new rule which checks slice bounds access (reslicing and indexing) to ensure that slices are not accessed out of bounds. This only works for slice bounds defined by a `make([]..., len)` or `make([]..., len, capacity)` where len/capacity is defined as a literal integer. For example it works for:
```go
s := make([]float, 10, 20)
```
But not for:
```go
s := make([]float, 10*3)
```
Since we don't evaluate expressions. It also will calculate and validate slice capacities for new slices made by reslicing when possible, such as:
```go
s := make([]float, 10)
x := s[5:]
```
The capacity for the new slice, `x`, will be validated in any subsequent usage. In addition, slices passed to functions are validated when possible by storing …

Feature: G602 Slice Bound Checking

---

cmd/gosec/main.go

The new flag '-terse' will only show the results and summary ignoring any logs occurred during a scan.
fixes #985

Add a new flag terse to show only the results and summary

---

action.yml

This version bump fixes go version 1.21.0

Update gosec image version to 2.17.0 in the Github action

---

Makefile
rules/implicit_aliasing.go
testutils/source.go

Updates https://github.com/securego/gosec/issues/966

Ignore struct pointers in G601

---

rules/slice_bounds.go
testutils/source.go

This exclude maps type form slice bounds checks. 
This is a partial fix for #1005

Exclude maps from slince bounce check rule

---

rules/hardcoded_credentials.go
testutils/source.go

Fix hardcoded_credentials rule to only match on more specific patterns

---

README.md
rules/fileperms.go
rules/rulelist.go
testutils/source.go

It seems that the os.Create will create by default a file with 0666 permissions.
This should be detected when the configured permissions are less than 0666. By default will not detect this case
unless the more restrictive mode is configured.
fixes #1019

Add a new rule which detects when a file is created with os.Create but the configured permissions are less than 0666

---

README.md
cmd/tlsconfig/tlsconfig.go
helpers.go
issue/issue_test.go
report/sarif/builder.go

This PR corrects spelling mistakes.

Fix typos in struct fields, comments, vars, and docs

---

analyzer.go
analyzers/slice_bounds.go

Restrict the maximum depth when tracking the slice bounds

---

analyzer.go
analyzer_test.go
cmd/tlsconfig/tlsconfig.go
issue/issue.go
testutils/pkg.go

Track ignored issues using file location instead of a AST node. There are issues linked to a different AST node than the original node used to start the scan.
fixes #1041

Refactor how ignored issues are tracked

---

README.md
analyzer.go
analyzer_test.go

- Ensure the ignores are parsed before analysing the package
- Update README with details which describe the current behaviour of #nosec
fixes #1046

Improve suppressions handling

---

Makefile
analyzer.go

- Fix data race in the analyzer
- Run the gosec with data race detector active during tests
fixes #1049

Fix data race in analyzer

---

analyzer.go

We should use `(*regexp.Regexp).MatchString` instead of `(*regexp.Regexp).Match([]byte(...))` when matching string to avoid unnecessary `[]byte` conversions and reduce allocations. A one-line change for free performance improvement.
Example benchmark:
```go
var defaultTagRegex = regexp.MustCompile("\n *#nosec")
func BenchmarkMatch(b *testing.B) {
for i := 0; i < b.N; i++ {
if match := defaultTagRegex.Match([]byte("\n #nosec")); !match {
b.Fail()
}
}
}
func BenchmarkMatchString(b *testing.B) {
for i := 0; i < b.N; i++ {
if match := defaultTagRegex.MatchString("\n #nosec"); !match {
b.Fail()
}
}
}
```
Result:
```
goos: linux
goarch: amd64
pkg: github.com/securego/gosec/v2
cpu: AMD Ryzen 7 PRO 4750U with Radeon Graphics
BenchmarkMatch-16          	 5367033	       210.6 ns/op	       8 B/op …
```

Avoid allocations with `(*regexp.Regexp).MatchString`

---

Makefile

Remove the hardcoded GOOS value when building the Linux binary to enable support for container image for ARM

---

analyzer.go
testutils/source.go

Ensure ignores are handled properly for multi-line issues

---

.github/workflows/release.yml
.goreleaser.yml

Hello Team,
I've updated the specified files to enable the release of ppc64le binaries and docker image for gosec.
- Updated **.github/workflows/release.yml** & **.goreleaser.yml** to support Linux on IBM Power ( ppc64le )
Signed-off-by: Pooja Shah [Pooja.Shah4@ibm.com](mailto:Pooja.Shah4@ibm.com)

Added ppc64le support

---

README.md

GitHub action upload-sarif v1 is deprecated and action fails if used. Updated README with v2 so workflow can be copy and use without modiciations
Fixes #1077

Update README with upload-sarif v2

---

rules/hardcoded_credentials.go

While looking for the regex associated with harcoded credentials, I noticed that the `Stripe API Key` one seemed to be duplicated. This Pull request aims to remove the duplicate.

fix(hardcoded): remove duplicated `Stripe API Key`

---

README.md
rules/implicit_aliasing.go

After the recent changes in language in Go 1.22 we no longer need to check for "implicit memory aliasing" rule. Doing:
```
for _, item := range items {
cpItem = &item
break
}
```
is now valid because `item` is a new variable in memory for every iteration (and not as it was before the same variable in memory what caused all the problems).
Closes: https://github.com/securego/gosec/issues/1090

Ignore 'implicit memory aliasing' rule for Go 1.22+

---

import_tracker.go
rules/rand.go
testutils/g404_samples.go

Fix for issue #1109
- Add support for math/rand/v2 to the existing rule (G404).
- Modified the function used to extract import names to handle paths with version information.

Add support for math/rand/v2 added in Go 1.22

---

analyzer.go
analyzer_test.go

As of Go1.21, we can utilize standard package function [`ast.IsGenerated`](https://pkg.go.dev/go/ast#IsGenerated) to check if a file is generated or not. This PR replace `isGeneratedFile` with that new standard function.
Second commit updates test source. 
Standard `ast.IsGenerated` returns `false` for original test sources, because it does not comply with
https://pkg.go.dev/cmd/go#hdr-Generate_Go_files_by_processing_source
> This line must appear before the first non-comment, non-blank text in the file.
Original test source does not satisfy this condition, so original `isGeneratedFile` function returns `true` when it should return `false`.
I would assume we should update the test cases, but this change can be breaking for some users. I wonder if we should do that.

Use standard function to check if a file is generated

---

helpers.go

This PR introduce changes on how the go version is extracted.
The version is now extracted from the linted module instead of the runtime used to build the CLI.

fix(helpers/goversion): get from go.mod

---

rules/readfile.go

Add filepath.EvalSymlinks to clean functions in rule G304

---

README.md
helpers.go

Add an environment variable which disables the parsing of Go version from the module file present in the project

---

README.md
helpers.go

Add an environment variable which overrides the Go version detection

---

.gitignore
.golangci.yml
README.md
analyzers/conversion_overflow.go
analyzers/util.go
rules/rules_test.go
testutils/g103_samples.go
testutils/g109_samples.go
testutils/g115_samples.go

Add a new rule to detect integer overflow when converting between integer types

---

rules/templates.go

Add additional types such as CSS, JSStr and Srcset to the template rule. These types are marked as a security risk in the godoc https://pkg.go.dev/html/template.
fixes #496

Add more types to templates rule

---

analyzer.go
analyzer_test.go
testutils/g101_samples.go

Handle properly nosec directive when applied to a block or as a single line on a multi-line issue.
fixes #1105

Fix nosec directive when applied to a block

---

cmd/gosec/main.go

Allow enabling audit mode from the cli

Add -enable-audit cli flag

---

analyzer.go
testutils/g115_samples.go

On `master`, `#nosec G115` will not work if your package has multiple files. This appears to be because the ignores populated in `CheckRules` are cleared after every file. These ignores are needed in the `CheckAnalyzers` call that happen after `CheckRules`.
Fix this by not clearing the ignores every loop. All tests cases appear to still pass:
```
ginkgo run
<snip>
Ran 144 of 144 Specs in 6.095 seconds
SUCCESS! -- 144 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
```

Fix multifile analyzer ignores

---

analyzers/conversion_overflow.go
testutils/g115_samples.go

Calling `Underlying()` will get the underlying type [if there is one](https://github.com/golang/go/blob/959b3fd4265d7e4efb18af454cd18799ed70b8fe/src/go/types/alias.go#L50).
This allows correctly testing for overflows with type aliases.

Resolve underlying type to detect overflows in type aliases

---

analyzer.go
analyzer_test.go
analyzers/analyzers_set.go
analyzers/analyzers_test.go
analyzers/analyzerslist.go
analyzers/anaylzers_suite_test.go
analyzers/util.go
cmd/gosec/main.go
rules/rules_test.go
testutils/g103_samples.go
testutils/g109_samples.go

* This change does not exclude analyzers for inline comment
* Changed the expected issues count for G103, G109. Previously G115 has been included in those issues count.
* Show analyzers IDs(G115, G602) in gosec usage help
* See #1175
fixes #1175

Allow excluding analyzers globally

---

.golangci.yml
testutils/g115_samples.go

Add more test to cover more use cases for G115 rule

---

analyzers/conversion_overflow.go
testutils/g115_samples.go

Fix false positive in conversion overflow check from uint8/int8 type

---

analyzers/conversion_overflow.go
testutils/g115_samples.go

This pull request hopefully fixes the issue of false positives in the overflow analysis whenever bounds checks are performed or the size is already pre-determined.
**Disclaimer:**
This is my first time contributing to any linter and I don't consider myself being an AST wizard so please be more cautious when reviewing this code. 
fixes #1187

Fix conversion overflow false positives

---

analyzers/conversion_overflow.go
testutils/g115_samples.go

Extends the check for ParseInt (with proper bit size) to ParseUint.
Two tests were added.
1. To check that ParseUint does not cause a false positive
2. To check that ParseInt causes a true positive when casting to unsigned

Fix conversion overflow false positive when using ParseUint

---

analyzers/slice_bounds.go
testutils/g602_samples.go

Trying to fix  #1200 with this PR.
Suggestions/comments more than welcome

fix: G602 support for nested conditionals with bounds check

---

analyzers/conversion_overflow.go
analyzers/conversion_overflow_test.go
go.mod
go.sum
testutils/g115_samples.go

As per discussion in #1187, the implementation was lacking. This PR extends the bounds check logic to validate that the integer size is checked within the bounds of the destination type. 
I'd like to hear @rittneje's opinion on the changes as they reported the issues with it and @ben-krieger's too since he is already looking into it as well.
fixes #1187 
fixes #1202

Improvement the int conversion overflow logic to handle bound checks

---

analyzers/conversion_overflow.go
testutils/g115_samples.go

Similarly to the arithmetic example in #1212, the value being checked is, according to the SSA, different from the value being converted. So we have to be a bit smarter. Not as smart as with the arithmetic though.
I also found that explicit checks are still lacking, I partly fixed them and I'll document the rest in the issue.

G115 Struct Attribute Checks

---

analyzers/analyzerslist.go
cmd/gosec/main.go
rules/rulelist.go

Fixes #1230 
(also a few typo and unclear docs while tracking down the code)

Fix running single analyzer which isn't a rule bug

---

analyzers/conversion_overflow.go

Fixes #1229 
(or to be more correct... prevents it yet it's suspicious, see comments in the issue)

Prevent panic: unexpected constant value: <nil>

---

.goreleaser.yml
action.yml

- Add the version into goreleaser config
- Update the gosec to v2.21.4 in the Github action**

Update gosec to v1.21.4 in GitHub action

---

analyzers/conversion_overflow.go
testutils/g115_samples.go

Fixes the issue I recently found in https://github.com/securego/gosec/issues/1212#issuecomment-2499375351.
When converting to an `int*` from a `uint64` created by `strconv.ParseUint` with a specified bit size less than the size of the destination integer, currently G115 is falsely triggered. 
That's because the current check only allows the source and destination sign to match (i.e. from int* to int* or uint* to uint*). This is a useful check when going from `ParseInt` to a uint*, but when going from `ParseUint` to an int* the conversion is safe as long as the bit size is at least one less.
I've added the extra test and documented it since the logic is somewhat complex.
I've also added a few test cases to catch regressions.

Fix G115 false positive when going from parsed uint to larger int

---

analyzers/hardcoded_nonce.go
testutils/g407_samples.go

The nonce in the decryption functions/methods is typically provided and it should not be randomly generated.
fixes #1209

Remove the decryption funtions/methods from G407 check

---

analyzers/conversion_overflow.go
analyzers/hardcoded_nonce.go
rules/fileperms.go

This PR corrects spelling mistakes.

Fix typos in comments and fields

---

.golangci.yml
analyzers/conversion_overflow.go
go.mod
go.sum

The PR fixes `revive.redefines-builtin-id` lint warnings:
```sh
❯ golangci-lint run
analyzers/conversion_overflow.go:144:2: redefines-builtin-id: redefinition of the built-in function min (revive)
var min int
^
analyzers/conversion_overflow.go:145:2: redefines-builtin-id: redefinition of the built-in function max (revive)
var max uint
^
analyzers/conversion_overflow.go:155:3: redefines-builtin-id: redefinition of the built-in function max (revive)
max = (1 << uint(shiftAmount)) - 1
^
analyzers/conversion_overflow.go:156:3: redefines-builtin-id: redefinition of the built-in function min (revive)
min = -1 << (intSize - 1)
^
analyzers/conversion_overflow.go:159:3: redefines-builtin-id: redefinition of the built-in function max (revive)
max = (1 << uint(intSize)) - 1
^ …
```

fix: revive.redefines-builtin-id lint warnings

---

CONTRIBUTING.md
README.md

Add some docs for developers who want to extend gosec-- this is based on my personal notes I took while attempting to add a taint analyzer (it didn't pan out, but I intend to keep looking into it).
I've also drawn a diagram in miro, which I will add in a future PR once I figure out how to export it to useful file format.

Documentation on adding new rules and analyzers

---

analyzer_test.go
helpers_test.go

The PR refactors tests by replacing `os.MkdirTemp` with `GinkgoT().TempDir()`.
[`T.TempDir`](https://pkg.go.dev/testing#T.TempDir) returns a temporary directory for the test to use. The directory is automatically removed when the test and all its subtests complete.

Simplify tests by using GinkgoT().TempDir()

---

go.mod
go.sum
tools/tools.go

The PR removes `golang.org/x/lint` dependency because it's not used at all.

Remove unused golint dependency

---

cmd/gosec/main.go

This is for consistency with other flags.
`gosec -v` before:
```
OPTIONS:
-ai-api-key string
key to access the AI API
-ai-api-provider string
AI API provider to generate auto fixes to issues.
Valid options are: gemini
-ai-endpoint string
endpoint AI API.
This is optional, the default API endpoint will be used when not provided.
-color
Prints the text format report with colorization when it goes in the stdout (default true)
```
`go run ./cmd/gosec -v` after:
```
OPTIONS:
-ai-api-key string
Key to access the AI API
-ai-api-provider string
AI API provider to generate auto fixes to issues.
Valid options are: gemini
-ai-endpoint string
Endpoint AI API.
This is optional, the default API endpoint will be used when not provided.
-color
Prints the text format report with colorization when it goes …
```

Improve capitalization in AI API flags descriptions

---

analyzer.go

This PR is intended to increase readability and maintainability of the `Analyzer.ignore` unexported function.

Simplify Analyzer.ignore by reducing nesting

---

analyzer.go

The PR replaces `regexp.MustCompile` with `strings.Contains` to simplify and performance.
These simple benchmark show, that version with `strings.Contains` is more performant.
<details>
<summary>Benchmark</summary>
```go
func BenchmarkAppendError(b *testing.B) {
analyzer := gosec.NewAnalyzer(nil, false, false, false, 1, nil)
file := "test.go"
err := errors.New("test error")
for i := 0; i < b.N; i++ {
analyzer.AppendError(file, err)
}
}
```
</details>
Before (`regexp.MustCompile`):
```
-test.shuffle 1734344546323474000
goos: darwin
goarch: arm64
pkg: github.com/securego/gosec/v2
cpu: Apple M1 Pro
BenchmarkAppendError
BenchmarkAppendError-8   	   33993	     35043 ns/op	    3927 B/op	      23 allocs/op
PASS
coverage: 3.7% of statements
ok  	github.com/securego/gosec/v2	3.471s
```
After …

Refactor AppendError to use strings.Contains

---

README.md
rules/implicit_aliasing.go
testutils/g402_samples.go

The PR updates the links to `https://go.dev` across the code.

Replace old golang.org links with new go.dev

---

README.md
RULES.md

More docs updates for ya'll. If you'd prefer I open issues before making PRs let me know.

Rule documentation updates

---

analyzer.go
analyzer_test.go

This PR refactors `Analyzer.AppendError` to handle [`build.NoGoError`](https://pkg.go.dev/go/build#NoGoError) for non-buildable packages. It's better to check for specific error instead of string.

Refactor AppendError to check for build.NoGoError

---

.golangci.yml
autofix/ai_test.go

This PR improves the tests in `autofix/ai_test.go`.
Changes:
- Added `testifylint` to the list of linters.
- Replaced `assert.Error` and `assert.Equal` with `require.ErrorEqual` as suggested by `testifylint`.
- Updated mock expectations to use `.Once()`.
- Changed to use `mock.AssertExpectationsForObjects`.

Enable testifylint and fix up lint issues

---

cmd/gosec/sort_issues.go

With the help of [`slices.SortFunc`](https://pkg.go.dev/slices@go1.22#SortFunc) and the [`cmp`](https://pkg.go.dev/cmp@go1.22) package, this PR simplifies the implementation of `sortIssues`.

Simplify sortIssues implementation

---

rules/errors.go

The PR removes the dot from the "What" message for the G104 rule to make it consistent with the rest of the rule messages.

Update what message for G104

---

testutils/g115_samples.go

Add test to conver unit parssing for G115 rule

---

README.md
analyzer.go
analyzer_test.go
testutils/g101_samples.go
testutils/g112_samples.go

Add support for `//gosec:disable` directive

---

action.yml

Hello! 👋 
This change is needed for GitHub Actions to pull the correct version. Ideally this would get merged before the release is created, so Dependabot pulls the right version when updating GitHub Actions.

Update version in 'action.yml' to 2.22.3 (anticipating next version)

---

Makefile

fixes #1343 
The version flag command didn't showed proper version or gittag when checked, this PR address that issue by including the data during compile time by passing the LD flags
Result:

updated the -version flag metadata by updating build command

---

report/sarif/builder.go

as noted in #1393 and stated in the schema https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/sarif-v2.1.0-errata01-os-complete.html#_Toc141790720 (considering this is the right version) Text SHALL be present when Markdown is used. This PR just uses the autofix for text right now. A further issue can be opened if the autofix is indeed markdown but for now this PR should at least enable SRAIF upload again
Fixes https://github.com/securego/gosec/issues/1393

fix: text must be supplied when markdown is used

---

analyzers/slice_bounds.go
testutils/g602_samples.go

check nil slices, partially check bounds
